/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as HomeRouteImport } from './routes/home'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as CategoryCategoryRouteImport } from './routes/category.$category'
import { Route as GamingSpinRouteImport } from './routes/gaming.spin'
import { Route as ResultQuizIdRouteImport } from './routes/result.$quizId'
import { Route as RulesCategoryRouteImport } from './routes/rules.$category'
import { Route as QuizCategoryTopicRouteImport } from './routes/quiz.$category.$topic'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoryCategoryRoute = CategoryCategoryRouteImport.update({
  id: '/category/$category',
  path: '/category/$category',
  getParentRoute: () => rootRouteImport,
} as any)
const GamingSpinRoute = GamingSpinRouteImport.update({
  id: '/gaming/spin',
  path: '/gaming/spin',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultQuizIdRoute = ResultQuizIdRouteImport.update({
  id: '/result/$quizId',
  path: '/result/$quizId',
  getParentRoute: () => rootRouteImport,
} as any)
const RulesCategoryRoute = RulesCategoryRouteImport.update({
  id: '/rules/$category',
  path: '/rules/$category',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizCategoryTopicRoute = QuizCategoryTopicRouteImport.update({
  id: '/quiz/$category/$topic',
  path: '/quiz/$category/$topic',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/categories': typeof CategoriesRoute
  '/history': typeof HistoryRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/category/$category': typeof CategoryCategoryRoute
  '/gaming/spin': typeof GamingSpinRoute
  '/result/$quizId': typeof ResultQuizIdRoute
  '/rules/$category': typeof RulesCategoryRoute
  '/quiz/$category/$topic': typeof QuizCategoryTopicRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/categories': typeof CategoriesRoute
  '/history': typeof HistoryRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/category/$category': typeof CategoryCategoryRoute
  '/gaming/spin': typeof GamingSpinRoute
  '/result/$quizId': typeof ResultQuizIdRoute
  '/rules/$category': typeof RulesCategoryRoute
  '/quiz/$category/$topic': typeof QuizCategoryTopicRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/categories': typeof CategoriesRoute
  '/history': typeof HistoryRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/category/$category': typeof CategoryCategoryRoute
  '/gaming/spin': typeof GamingSpinRoute
  '/result/$quizId': typeof ResultQuizIdRoute
  '/rules/$category': typeof RulesCategoryRoute
  '/quiz/$category/$topic': typeof QuizCategoryTopicRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/categories'
    | '/history'
    | '/home'
    | '/login'
    | '/profile'
    | '/category/$category'
    | '/gaming/spin'
    | '/result/$quizId'
    | '/rules/$category'
    | '/quiz/$category/$topic'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/categories'
    | '/history'
    | '/home'
    | '/login'
    | '/profile'
    | '/category/$category'
    | '/gaming/spin'
    | '/result/$quizId'
    | '/rules/$category'
    | '/quiz/$category/$topic'
  id:
    | '__root__'
    | '/'
    | '/categories'
    | '/history'
    | '/home'
    | '/login'
    | '/profile'
    | '/category/$category'
    | '/gaming/spin'
    | '/result/$quizId'
    | '/rules/$category'
    | '/quiz/$category/$topic'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CategoriesRoute: typeof CategoriesRoute
  HistoryRoute: typeof HistoryRoute
  HomeRoute: typeof HomeRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  CategoryCategoryRoute: typeof CategoryCategoryRoute
  GamingSpinRoute: typeof GamingSpinRoute
  ResultQuizIdRoute: typeof ResultQuizIdRoute
  RulesCategoryRoute: typeof RulesCategoryRoute
  QuizCategoryTopicRoute: typeof QuizCategoryTopicRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$category': {
      id: '/category/$category'
      path: '/category/$category'
      fullPath: '/category/$category'
      preLoaderRoute: typeof CategoryCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gaming/spin': {
      id: '/gaming/spin'
      path: '/gaming/spin'
      fullPath: '/gaming/spin'
      preLoaderRoute: typeof GamingSpinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/result/$quizId': {
      id: '/result/$quizId'
      path: '/result/$quizId'
      fullPath: '/result/$quizId'
      preLoaderRoute: typeof ResultQuizIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rules/$category': {
      id: '/rules/$category'
      path: '/rules/$category'
      fullPath: '/rules/$category'
      preLoaderRoute: typeof RulesCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/$category/$topic': {
      id: '/quiz/$category/$topic'
      path: '/quiz/$category/$topic'
      fullPath: '/quiz/$category/$topic'
      preLoaderRoute: typeof QuizCategoryTopicRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CategoriesRoute: CategoriesRoute,
  HistoryRoute: HistoryRoute,
  HomeRoute: HomeRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  CategoryCategoryRoute: CategoryCategoryRoute,
  GamingSpinRoute: GamingSpinRoute,
  ResultQuizIdRoute: ResultQuizIdRoute,
  RulesCategoryRoute: RulesCategoryRoute,
  QuizCategoryTopicRoute: QuizCategoryTopicRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
